baseurl = "/"
languageCode = 'ja-JP'
title = 'Miura Computer Club'
theme = 'terminal'
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 9

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "更新日"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

  [params.logo]
    logoText = "MIURA COMPUTER CLUB"
    logoHomeLink = "/"

   [menu]
    [[menu.main]]
      identifier = "a"
      name = "ホーム"
      url = "/"
      weight = 1
    [[menu.main]]
      identifier = "b"
      name = "お問い合わせ"
      url = "/contact"
      weight = 2
    [[menu.main]]
      identifier = "c"
      name = "学習内容"
      url = "/study"
      weight = 3      
    [[menu.main]]
      identifier = "d"
      name = "メンバー紹介"
      url = "/members"
      weight = 4      
    [[menu.main]]
      identifier = "e"
      name = "レッスン"
      url = "/lessons"
      weight = 5      
#    [[menu.main]]
#      identifier = "f"
#      name = "ゲーム"
#      url = "/games"
#      weight = 6      
#    [[menu.main]]
#      identifier = "g"
#      name = "作品"
#      url = "/creations"
#      weight = 7     
    [[menu.main]]
      identifier = "h"
      name = "先生募集"
      url = "/sensei"
      weight = 8      
    [[menu.main]]
      identifier = "i"
      name = "メデイア"
      url = "/media"
      weight = 9      
    [[menu.main]]
      identifier = "j"
      name = "INSTAGRAM"
      url = "https://www.instagram.com/miuracomputerclub"
      weight = 10      

[markup.goldmark.renderer]
unsafe = true
